name: Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  NODE_VERSION: '20.x'

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --only=production
      
    - name: Run pre-deployment tests
      run: |
        npm run test:ci
        
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        npx @railway/cli deploy --service shelfhelp-ai-${{ github.event.inputs.environment || 'production' }}
        
    - name: Wait for deployment
      run: sleep 30
      
    - name: Run health checks
      run: |
        echo "🏥 Running health checks..."
        # Add actual health check commands here
        
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Deployment to ${{ github.event.inputs.environment || 'production' }} successful"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Deployment to ${{ github.event.inputs.environment || 'production' }} failed"